// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.herong.rpc.netty.protobuf.demo3;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Command> {

    // required .example.Command.CommandType type = 1;
    /**
     * <code>required .example.Command.CommandType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .example.Command.CommandType type = 1;</code>
     */
    com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType getType();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code example.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Command> implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.github.herong.rpc.netty.protobuf.demo3.Commands.Command, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType value = com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.herong.rpc.netty.protobuf.demo3.Commands.internal_static_example_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.herong.rpc.netty.protobuf.demo3.Commands.internal_static_example_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.class, com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code example.Command.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEAT = 1;</code>
       */
      HEARTBEAT(0, 1),
      /**
       * <code>LOGIN_REQ = 2;</code>
       */
      LOGIN_REQ(1, 2),
      /**
       * <code>LOGIN_RESP = 3;</code>
       */
      LOGIN_RESP(2, 3),
      /**
       * <code>IQ_REQ = 4;</code>
       */
      IQ_REQ(3, 4),
      /**
       * <code>IQ_RESP = 5;</code>
       */
      IQ_RESP(4, 5),
      /**
       * <code>MESSAGE = 6;</code>
       */
      MESSAGE(5, 6),
      /**
       * <code>MESSAGE_ACK = 7;</code>
       */
      MESSAGE_ACK(6, 7),
      /**
       * <code>PRESENCE = 8;</code>
       */
      PRESENCE(7, 8),
      ;

      /**
       * <code>HEARTBEAT = 1;</code>
       */
      public static final int HEARTBEAT_VALUE = 1;
      /**
       * <code>LOGIN_REQ = 2;</code>
       */
      public static final int LOGIN_REQ_VALUE = 2;
      /**
       * <code>LOGIN_RESP = 3;</code>
       */
      public static final int LOGIN_RESP_VALUE = 3;
      /**
       * <code>IQ_REQ = 4;</code>
       */
      public static final int IQ_REQ_VALUE = 4;
      /**
       * <code>IQ_RESP = 5;</code>
       */
      public static final int IQ_RESP_VALUE = 5;
      /**
       * <code>MESSAGE = 6;</code>
       */
      public static final int MESSAGE_VALUE = 6;
      /**
       * <code>MESSAGE_ACK = 7;</code>
       */
      public static final int MESSAGE_ACK_VALUE = 7;
      /**
       * <code>PRESENCE = 8;</code>
       */
      public static final int PRESENCE_VALUE = 8;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 1: return HEARTBEAT;
          case 2: return LOGIN_REQ;
          case 3: return LOGIN_RESP;
          case 4: return IQ_REQ;
          case 5: return IQ_RESP;
          case 6: return MESSAGE;
          case 7: return MESSAGE_ACK;
          case 8: return PRESENCE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:example.Command.CommandType)
    }

    private int bitField0_;
    // required .example.Command.CommandType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType type_;
    /**
     * <code>required .example.Command.CommandType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .example.Command.CommandType type = 1;</code>
     */
    public com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType getType() {
      return type_;
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      type_ = com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType.HEARTBEAT;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.github.herong.rpc.netty.protobuf.demo3.Commands.Command>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.herong.rpc.netty.protobuf.demo3.Commands.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.github.herong.rpc.netty.protobuf.demo3.Commands.Command, Builder> implements com.github.herong.rpc.netty.protobuf.demo3.Commands.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.herong.rpc.netty.protobuf.demo3.Commands.internal_static_example_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.herong.rpc.netty.protobuf.demo3.Commands.internal_static_example_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.class, com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.Builder.class);
      }

      // Construct using com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType.HEARTBEAT;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.herong.rpc.netty.protobuf.demo3.Commands.internal_static_example_Command_descriptor;
      }

      public com.github.herong.rpc.netty.protobuf.demo3.Commands.Command getDefaultInstanceForType() {
        return com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.getDefaultInstance();
      }

      public com.github.herong.rpc.netty.protobuf.demo3.Commands.Command build() {
        com.github.herong.rpc.netty.protobuf.demo3.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.herong.rpc.netty.protobuf.demo3.Commands.Command buildPartial() {
        com.github.herong.rpc.netty.protobuf.demo3.Commands.Command result = new com.github.herong.rpc.netty.protobuf.demo3.Commands.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.herong.rpc.netty.protobuf.demo3.Commands.Command) {
          return mergeFrom((com.github.herong.rpc.netty.protobuf.demo3.Commands.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.herong.rpc.netty.protobuf.demo3.Commands.Command other) {
        if (other == com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.herong.rpc.netty.protobuf.demo3.Commands.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.herong.rpc.netty.protobuf.demo3.Commands.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .example.Command.CommandType type = 1;
      private com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType type_ = com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType.HEARTBEAT;
      /**
       * <code>required .example.Command.CommandType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .example.Command.CommandType type = 1;</code>
       */
      public com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType getType() {
        return type_;
      }
      /**
       * <code>required .example.Command.CommandType type = 1;</code>
       */
      public Builder setType(com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .example.Command.CommandType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.github.herong.rpc.netty.protobuf.demo3.Commands.Command.CommandType.HEARTBEAT;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:example.Command)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007example\"\316\001\n\007Command\022*\n\004" +
      "type\030\001 \002(\0162\034.example.Command.CommandType" +
      "\022\n\n\002id\030\002 \001(\005\"\200\001\n\013CommandType\022\r\n\tHEARTBEA" +
      "T\020\001\022\r\n\tLOGIN_REQ\020\002\022\016\n\nLOGIN_RESP\020\003\022\n\n\006IQ" +
      "_REQ\020\004\022\013\n\007IQ_RESP\020\005\022\013\n\007MESSAGE\020\006\022\017\n\013MESS" +
      "AGE_ACK\020\007\022\014\n\010PRESENCE\020\010*\010\010d\020\200\200\200\200\002B6\n*com" +
      ".github.herong.rpc.netty.protobuf.demo3B" +
      "\010Commands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_example_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_example_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_example_Command_descriptor,
              new java.lang.String[] { "Type", "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
